title: <p align="center"> Nguy Doan Toan </p>

logo: "/images/avatar.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.facebook.com/toan.nguy.520/">Facebook</a> |
  <a href="https://github.com/Doan-Toan">GitHub</a>
  </p>
  
  <p align="justify">
  I am a final year student at Sai Gon University and my major is Software Technology. 
  During my studies, I participated in a few projects with many programming languages, such as Python, Java, C++, Dart. 
  I am willing to improve the skills and knowledge necessary for my role.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
